/* tslint:disable */
/* eslint-disable */
/**
 * Data
 * With the Data service you can obtain additional data such as vehicle profiles.
 *
 * The version of the OpenAPI document: 1.17
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiChange } from './ApiChange';
import {
    ApiChangeFromJSON,
    ApiChangeFromJSONTyped,
    ApiChangeToJSON,
} from './ApiChange';

/**
 * 
 * @export
 * @interface ApiChanges
 */
export interface ApiChanges {
    /**
     * A list of API changes.
     * @type {Array<ApiChange>}
     * @memberof ApiChanges
     */
    apiChanges: Array<ApiChange>;
}

/**
 * Check if a given object implements the ApiChanges interface.
 */
export function instanceOfApiChanges(value: object): value is ApiChanges {
    if (!('apiChanges' in value) || value['apiChanges'] === undefined) return false;
    return true;
}

export function ApiChangesFromJSON(json: any): ApiChanges {
    return ApiChangesFromJSONTyped(json, false);
}

export function ApiChangesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiChanges {
    if (json == null) {
        return json;
    }
    return {
        
        'apiChanges': ((json['apiChanges'] as Array<any>).map(ApiChangeFromJSON)),
    };
}

export function ApiChangesToJSON(value?: ApiChanges | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'apiChanges': ((value['apiChanges'] as Array<any>).map(ApiChangeToJSON)),
    };
}

