/* tslint:disable */
/* eslint-disable */
/**
 * Data
 * With the Data service you can obtain additional data such as vehicle profiles.
 *
 * The version of the OpenAPI document: 1.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Physical properties of the battery regarding capacity and charging. It is null for an unpowered vehicle.
 * 
 * Relevant for `range calculation`.
 * @export
 * @interface Battery
 */
export interface Battery {
    /**
     * The total battery capacity [kWh].
     * @type {number}
     * @memberof Battery
     */
    totalCapacity: number;
    /**
     * Charging power AC [kW].
     * @type {number}
     * @memberof Battery
     */
    acChargingPower: number;
    /**
     * Charging power DC [kW].
     * @type {number}
     * @memberof Battery
     */
    dcChargingPower: number;
    /**
     * List of charging plugs the vehicle is compatible with.
     * @type {Array<string>}
     * @memberof Battery
     */
    plugs: Array<string>;
}

/**
 * Check if a given object implements the Battery interface.
 */
export function instanceOfBattery(value: object): value is Battery {
    if (!('totalCapacity' in value) || value['totalCapacity'] === undefined) return false;
    if (!('acChargingPower' in value) || value['acChargingPower'] === undefined) return false;
    if (!('dcChargingPower' in value) || value['dcChargingPower'] === undefined) return false;
    if (!('plugs' in value) || value['plugs'] === undefined) return false;
    return true;
}

export function BatteryFromJSON(json: any): Battery {
    return BatteryFromJSONTyped(json, false);
}

export function BatteryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Battery {
    if (json == null) {
        return json;
    }
    return {
        
        'totalCapacity': json['totalCapacity'],
        'acChargingPower': json['acChargingPower'],
        'dcChargingPower': json['dcChargingPower'],
        'plugs': json['plugs'],
    };
}

export function BatteryToJSON(value?: Battery | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'totalCapacity': value['totalCapacity'],
        'acChargingPower': value['acChargingPower'],
        'dcChargingPower': value['dcChargingPower'],
        'plugs': value['plugs'],
    };
}

