/* tslint:disable */
/* eslint-disable */
/**
 * Data
 * With the Data service you can obtain additional data such as vehicle profiles.
 *
 * The version of the OpenAPI document: 1.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The position around which to scan for combined transports in the map data. This parameter is mutually exclusive with **text**.
 * @export
 * @interface CombinedTransportByPosition
 */
export interface CombinedTransportByPosition {
    /**
     * The latitude value in degrees (WGS84/EPSG:4326) from south to north.
     * @type {number}
     * @memberof CombinedTransportByPosition
     */
    latitude: number;
    /**
     * The longitude value in degrees (WGS84/EPSG:4326) from west to east.
     * @type {number}
     * @memberof CombinedTransportByPosition
     */
    longitude: number;
    /**
     * The circle defined by the given point and this radius [m] in which to scan for combined transports.
     * @type {number}
     * @memberof CombinedTransportByPosition
     */
    radius?: number;
}

/**
 * Check if a given object implements the CombinedTransportByPosition interface.
 */
export function instanceOfCombinedTransportByPosition(value: object): value is CombinedTransportByPosition {
    if (!('latitude' in value) || value['latitude'] === undefined) return false;
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    return true;
}

export function CombinedTransportByPositionFromJSON(json: any): CombinedTransportByPosition {
    return CombinedTransportByPositionFromJSONTyped(json, false);
}

export function CombinedTransportByPositionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CombinedTransportByPosition {
    if (json == null) {
        return json;
    }
    return {
        
        'latitude': json['latitude'],
        'longitude': json['longitude'],
        'radius': json['radius'] == null ? undefined : json['radius'],
    };
}

export function CombinedTransportByPositionToJSON(value?: CombinedTransportByPosition | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'radius': value['radius'],
    };
}

