/* tslint:disable */
/* eslint-disable */
/**
 * Data
 * With the Data service you can obtain additional data such as vehicle profiles.
 *
 * The version of the OpenAPI document: 1.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomRoadAttributeScenario } from './CustomRoadAttributeScenario';
import {
    CustomRoadAttributeScenarioFromJSON,
    CustomRoadAttributeScenarioFromJSONTyped,
    CustomRoadAttributeScenarioToJSON,
} from './CustomRoadAttributeScenario';

/**
 * A list of custom road attribute scenarios.
 * @export
 * @interface CustomRoadAttributeScenarioList
 */
export interface CustomRoadAttributeScenarioList {
    /**
     * 
     * @type {Array<CustomRoadAttributeScenario>}
     * @memberof CustomRoadAttributeScenarioList
     */
    customRoadAttributeScenarios?: Array<CustomRoadAttributeScenario>;
}

/**
 * Check if a given object implements the CustomRoadAttributeScenarioList interface.
 */
export function instanceOfCustomRoadAttributeScenarioList(value: object): value is CustomRoadAttributeScenarioList {
    return true;
}

export function CustomRoadAttributeScenarioListFromJSON(json: any): CustomRoadAttributeScenarioList {
    return CustomRoadAttributeScenarioListFromJSONTyped(json, false);
}

export function CustomRoadAttributeScenarioListFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomRoadAttributeScenarioList {
    if (json == null) {
        return json;
    }
    return {
        
        'customRoadAttributeScenarios': json['customRoadAttributeScenarios'] == null ? undefined : ((json['customRoadAttributeScenarios'] as Array<any>).map(CustomRoadAttributeScenarioFromJSON)),
    };
}

export function CustomRoadAttributeScenarioListToJSON(value?: CustomRoadAttributeScenarioList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'customRoadAttributeScenarios': value['customRoadAttributeScenarios'] == null ? undefined : ((value['customRoadAttributeScenarios'] as Array<any>).map(CustomRoadAttributeScenarioToJSON)),
    };
}

