/* tslint:disable */
/* eslint-disable */
/**
 * Data
 * With the Data service you can obtain additional data such as vehicle profiles.
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The engine type of the vehicle.
 * 
 * Relevant for `toll`, `emissions`.
 * @export
 */
export const EngineType = {
    COMBUSTION: 'COMBUSTION',
    ELECTRIC: 'ELECTRIC',
    HYBRID: 'HYBRID'
} as const;
export type EngineType = typeof EngineType[keyof typeof EngineType];


export function EngineTypeFromJSON(json: any): EngineType {
    return EngineTypeFromJSONTyped(json, false);
}

export function EngineTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EngineType {
    return json as EngineType;
}

export function EngineTypeToJSON(value?: EngineType | null): any {
    return value as any;
}

