/* tslint:disable */
/* eslint-disable */
/**
 * Data
 * With the Data service you can obtain additional data such as vehicle profiles.
 *
 * The version of the OpenAPI document: 1.17
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LowEmissionZoneFeatures } from './LowEmissionZoneFeatures';
import {
    LowEmissionZoneFeaturesFromJSON,
    LowEmissionZoneFeaturesFromJSONTyped,
    LowEmissionZoneFeaturesToJSON,
} from './LowEmissionZoneFeatures';

/**
 * Lists the available data and their features for the map.
 * @export
 * @interface Features
 */
export interface Features {
    /**
     * 
     * @type {LowEmissionZoneFeatures}
     * @memberof Features
     */
    lowEmissionZoneFeatures: LowEmissionZoneFeatures;
}

/**
 * Check if a given object implements the Features interface.
 */
export function instanceOfFeatures(value: object): value is Features {
    if (!('lowEmissionZoneFeatures' in value) || value['lowEmissionZoneFeatures'] === undefined) return false;
    return true;
}

export function FeaturesFromJSON(json: any): Features {
    return FeaturesFromJSONTyped(json, false);
}

export function FeaturesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Features {
    if (json == null) {
        return json;
    }
    return {
        
        'lowEmissionZoneFeatures': LowEmissionZoneFeaturesFromJSON(json['lowEmissionZoneFeatures']),
    };
}

export function FeaturesToJSON(value?: Features | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'lowEmissionZoneFeatures': LowEmissionZoneFeaturesToJSON(value['lowEmissionZoneFeatures']),
    };
}

