/* tslint:disable */
/* eslint-disable */
/**
 * Data
 * With the Data service you can obtain additional data such as vehicle profiles.
 *
 * The version of the OpenAPI document: 1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const HazardousMaterials = {
    HAZARDOUS_TO_WATER: 'HAZARDOUS_TO_WATER',
    EXPLOSIVE: 'EXPLOSIVE',
    FLAMMABLE: 'FLAMMABLE',
    RADIOACTIVE: 'RADIOACTIVE',
    INHALATION_HAZARD: 'INHALATION_HAZARD',
    MEDICAL_WASTE: 'MEDICAL_WASTE',
    OTHER: 'OTHER'
} as const;
export type HazardousMaterials = typeof HazardousMaterials[keyof typeof HazardousMaterials];


export function HazardousMaterialsFromJSON(json: any): HazardousMaterials {
    return HazardousMaterialsFromJSONTyped(json, false);
}

export function HazardousMaterialsFromJSONTyped(json: any, ignoreDiscriminator: boolean): HazardousMaterials {
    return json as HazardousMaterials;
}

export function HazardousMaterialsToJSON(value?: HazardousMaterials | null): any {
    return value as any;
}

