/* tslint:disable */
/* eslint-disable */
/**
 * Data
 * With the Data service you can obtain additional data such as vehicle profiles.
 *
 * The version of the OpenAPI document: 1.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const LowEmissionZoneTypes = {
    DE_GREEN: 'DE_GREEN',
    DE_YELLOW: 'DE_YELLOW',
    DE_RED: 'DE_RED',
    DE_NONE: 'DE_NONE'
} as const;
export type LowEmissionZoneTypes = typeof LowEmissionZoneTypes[keyof typeof LowEmissionZoneTypes];


export function LowEmissionZoneTypesFromJSON(json: any): LowEmissionZoneTypes {
    return LowEmissionZoneTypesFromJSONTyped(json, false);
}

export function LowEmissionZoneTypesFromJSONTyped(json: any, ignoreDiscriminator: boolean): LowEmissionZoneTypes {
    return json as LowEmissionZoneTypes;
}

export function LowEmissionZoneTypesToJSON(value?: LowEmissionZoneTypes | null): any {
    return value as any;
}

