/* tslint:disable */
/* eslint-disable */
/**
 * Data
 * With the Data service you can obtain additional data such as vehicle profiles.
 *
 * The version of the OpenAPI document: 1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PredefinedVehicleProfile,
    PredefinedVehicleProfileFromJSON,
    PredefinedVehicleProfileFromJSONTyped,
    PredefinedVehicleProfileToJSON,
} from './';

/**
 * 
 * @export
 * @interface PredefinedVehicleProfiles
 */
export interface PredefinedVehicleProfiles {
    /**
     * A list of predefined vehicle profiles.
     * @type {Array<PredefinedVehicleProfile>}
     * @memberof PredefinedVehicleProfiles
     */
    profiles: Array<PredefinedVehicleProfile>;
}

export function PredefinedVehicleProfilesFromJSON(json: any): PredefinedVehicleProfiles {
    return PredefinedVehicleProfilesFromJSONTyped(json, false);
}

export function PredefinedVehicleProfilesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PredefinedVehicleProfiles {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'profiles': ((json['profiles'] as Array<any>).map(PredefinedVehicleProfileFromJSON)),
    };
}

export function PredefinedVehicleProfilesToJSON(value?: PredefinedVehicleProfiles | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'profiles': ((value.profiles as Array<any>).map(PredefinedVehicleProfileToJSON)),
    };
}


