/* tslint:disable */
/* eslint-disable */
/**
 * Data
 * With the Data service you can obtain additional data such as vehicle profiles.
 *
 * The version of the OpenAPI document: 1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The region in this profile is designed for. It represents the characteristics of its region.
 * See the [profiles concept](./concepts/profiles) for details.
 * @export
 */
export const RegionType = {
    EUROPE: 'EUROPE',
    AMERICA: 'AMERICA',
    AUSTRALIA: 'AUSTRALIA',
    IMEA: 'IMEA',
    WORLD: 'WORLD'
} as const;
export type RegionType = typeof RegionType[keyof typeof RegionType];


export function RegionTypeFromJSON(json: any): RegionType {
    return RegionTypeFromJSONTyped(json, false);
}

export function RegionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegionType {
    return json as RegionType;
}

export function RegionTypeToJSON(value?: RegionType | null): any {
    return value as any;
}

