/* tslint:disable */
/* eslint-disable */
/**
 * Data
 * With the Data service you can obtain additional data such as vehicle profiles.
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RoadAttributesResults = {
    POLYLINES: 'POLYLINES'
} as const;
export type RoadAttributesResults = typeof RoadAttributesResults[keyof typeof RoadAttributesResults];


export function RoadAttributesResultsFromJSON(json: any): RoadAttributesResults {
    return RoadAttributesResultsFromJSONTyped(json, false);
}

export function RoadAttributesResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoadAttributesResults {
    return json as RoadAttributesResults;
}

export function RoadAttributesResultsToJSON(value?: RoadAttributesResults | null): any {
    return value as any;
}

