/*
 * Data
 *
 * With the Data service you can obtain additional data such as vehicle profiles.
 *
 * The version of the OpenAPI document: 1.12
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.data.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.data.Model
{
    /// <summary>
    /// A list of custom road attribute scenarios.
    /// </summary>
    [DataContract(Name = "CustomRoadAttributeScenarioList")]
    public partial class CustomRoadAttributeScenarioList : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomRoadAttributeScenarioList" /> class.
        /// </summary>
        /// <param name="customRoadAttributeScenarios">customRoadAttributeScenarios.</param>
        public CustomRoadAttributeScenarioList(List<CustomRoadAttributeScenario> customRoadAttributeScenarios = default(List<CustomRoadAttributeScenario>))
        {
            this.CustomRoadAttributeScenarios = customRoadAttributeScenarios;
        }

        /// <summary>
        /// Gets or Sets CustomRoadAttributeScenarios
        /// </summary>
        [DataMember(Name = "customRoadAttributeScenarios", EmitDefaultValue = false)]
        public List<CustomRoadAttributeScenario> CustomRoadAttributeScenarios { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CustomRoadAttributeScenarioList {\n");
            sb.Append("  CustomRoadAttributeScenarios: ").Append(CustomRoadAttributeScenarios).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
