/*
 * Data
 *
 * With the Data service you can obtain additional data such as vehicle profiles.
 *
 * The version of the OpenAPI document: 1.17
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.data.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.data.Model
{
    /// <summary>
    /// Lists the available data and their features for the map.
    /// </summary>
    [DataContract(Name = "Features")]
    public partial class Features : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Features" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Features() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Features" /> class.
        /// </summary>
        /// <param name="lowEmissionZoneFeatures">lowEmissionZoneFeatures (required).</param>
        public Features(LowEmissionZoneFeatures lowEmissionZoneFeatures = default(LowEmissionZoneFeatures))
        {
            // to ensure "lowEmissionZoneFeatures" is required (not null)
            if (lowEmissionZoneFeatures == null)
            {
                throw new ArgumentNullException("lowEmissionZoneFeatures is a required property for Features and cannot be null");
            }
            this.LowEmissionZoneFeatures = lowEmissionZoneFeatures;
        }

        /// <summary>
        /// Gets or Sets LowEmissionZoneFeatures
        /// </summary>
        [DataMember(Name = "lowEmissionZoneFeatures", IsRequired = true, EmitDefaultValue = true)]
        public LowEmissionZoneFeatures LowEmissionZoneFeatures { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Features {\n");
            sb.Append("  LowEmissionZoneFeatures: ").Append(LowEmissionZoneFeatures).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
