/*
 * Data
 *
 * With the Data service you can obtain additional data such as vehicle profiles.
 *
 * The version of the OpenAPI document: 1.13
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.data.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.data.Model
{
    /// <summary>
    /// PredefinedVehicleProfiles
    /// </summary>
    [DataContract(Name = "PredefinedVehicleProfiles")]
    public partial class PredefinedVehicleProfiles : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PredefinedVehicleProfiles" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PredefinedVehicleProfiles() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PredefinedVehicleProfiles" /> class.
        /// </summary>
        /// <param name="profiles">A list of predefined vehicle profiles. (required).</param>
        public PredefinedVehicleProfiles(List<PredefinedVehicleProfile> profiles = default(List<PredefinedVehicleProfile>))
        {
            // to ensure "profiles" is required (not null)
            if (profiles == null)
            {
                throw new ArgumentNullException("profiles is a required property for PredefinedVehicleProfiles and cannot be null");
            }
            this.Profiles = profiles;
        }

        /// <summary>
        /// A list of predefined vehicle profiles.
        /// </summary>
        /// <value>A list of predefined vehicle profiles.</value>
        [DataMember(Name = "profiles", IsRequired = true, EmitDefaultValue = true)]
        public List<PredefinedVehicleProfile> Profiles { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PredefinedVehicleProfiles {\n");
            sb.Append("  Profiles: ").Append(Profiles).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
