/*
 * Data
 *
 * With the Data service you can obtain additional data such as vehicle profiles.
 *
 * The version of the OpenAPI document: 1.12
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.data.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.data.Model
{
    /// <summary>
    /// ReleaseNotes
    /// </summary>
    [DataContract(Name = "ReleaseNotes")]
    public partial class ReleaseNotes : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReleaseNotes" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ReleaseNotes() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ReleaseNotes" /> class.
        /// </summary>
        /// <param name="varReleaseNotes">A list of release notes. (required).</param>
        public ReleaseNotes(List<ReleaseNote> varReleaseNotes = default(List<ReleaseNote>))
        {
            // to ensure "varReleaseNotes" is required (not null)
            if (varReleaseNotes == null)
            {
                throw new ArgumentNullException("varReleaseNotes is a required property for ReleaseNotes and cannot be null");
            }
            this.VarReleaseNotes = varReleaseNotes;
        }

        /// <summary>
        /// A list of release notes.
        /// </summary>
        /// <value>A list of release notes.</value>
        [DataMember(Name = "releaseNotes", IsRequired = true, EmitDefaultValue = true)]
        public List<ReleaseNote> VarReleaseNotes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReleaseNotes {\n");
            sb.Append("  VarReleaseNotes: ").Append(VarReleaseNotes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
