/*
 * Data
 *
 * With the Data service you can obtain additional data such as vehicle profiles.
 *
 * The version of the OpenAPI document: 1.10
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.data.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.data.Model
{
    /// <summary>
    /// The direction of the road the attributes apply to.  * &#x60;POLYLINE_DIRECTION&#x60; - Describes the direction from the start node to the end node of the polyline of the road.  * &#x60;REVERSE_POLYLINE_DIRECTION&#x60; - Describes the direction from the end node to the start node of the polyline of the road.  * &#x60;BOTH&#x60; - Describes both directions.  If the selection contains more than one road and the direction is different from _BOTH_, an error will be returned.
    /// </summary>
    /// <value>The direction of the road the attributes apply to.  * &#x60;POLYLINE_DIRECTION&#x60; - Describes the direction from the start node to the end node of the polyline of the road.  * &#x60;REVERSE_POLYLINE_DIRECTION&#x60; - Describes the direction from the end node to the start node of the polyline of the road.  * &#x60;BOTH&#x60; - Describes both directions.  If the selection contains more than one road and the direction is different from _BOTH_, an error will be returned.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum RoadDirectionType
    {
        /// <summary>
        /// Enum POLYLINE_DIRECTION for value: POLYLINE_DIRECTION
        /// </summary>
        [EnumMember(Value = "POLYLINE_DIRECTION")]
        POLYLINE_DIRECTION = 1,

        /// <summary>
        /// Enum REVERSE_POLYLINE_DIRECTION for value: REVERSE_POLYLINE_DIRECTION
        /// </summary>
        [EnumMember(Value = "REVERSE_POLYLINE_DIRECTION")]
        REVERSE_POLYLINE_DIRECTION = 2,

        /// <summary>
        /// Enum BOTH for value: BOTH
        /// </summary>
        [EnumMember(Value = "BOTH")]
        BOTH = 3
    }

}
