/*
 * Data
 *
 * With the Data service you can obtain additional data such as vehicle profiles.
 *
 * The version of the OpenAPI document: 1.18
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.data.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.data.Model
{
    /// <summary>
    /// Routing-relevant options which control the course of the route in detail.
    /// </summary>
    [DataContract(Name = "RouteOptions")]
    public partial class RouteOptions : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RouteOptions" /> class.
        /// </summary>
        /// <param name="maximumSpeed">The maximum speed of the vehicle [km/h]. The speeds for calculating the driving times on all roads will be limited to this value..</param>
        /// <param name="speedsByRoadCategory">The speeds used to calculate the driving times by road category. The first array element represents motorways, the last one pedestrian and cycle paths, see [here](./concepts/road-categories) for more information on road categories.  The speed actually used for a road segment depends on its road category and a speed category defined in the map data and is calculated by linear interpolation between the minimum and maximum speed..</param>
        /// <param name="timePreferenceOverDistance">Specifies the weighting between travel time and travel distance when calculating a route. The value defines the preference for minimizing travel time over minimizing travel distance. - 0: Route is optimized purely for shortest distance. - 100: Route is optimized purely for shortest travel time. - 1-99: A weighted combination of travel time and distance is applied, with higher values     giving more importance to travel time..</param>
        public RouteOptions(int? maximumSpeed = default(int?), List<SpeedByRoadCategory> speedsByRoadCategory = default(List<SpeedByRoadCategory>), int? timePreferenceOverDistance = default(int?))
        {
            this.MaximumSpeed = maximumSpeed;
            this.SpeedsByRoadCategory = speedsByRoadCategory;
            this.TimePreferenceOverDistance = timePreferenceOverDistance;
        }

        /// <summary>
        /// The maximum speed of the vehicle [km/h]. The speeds for calculating the driving times on all roads will be limited to this value.
        /// </summary>
        /// <value>The maximum speed of the vehicle [km/h]. The speeds for calculating the driving times on all roads will be limited to this value.</value>
        [DataMember(Name = "maximumSpeed", EmitDefaultValue = true)]
        public int? MaximumSpeed { get; set; }

        /// <summary>
        /// The speeds used to calculate the driving times by road category. The first array element represents motorways, the last one pedestrian and cycle paths, see [here](./concepts/road-categories) for more information on road categories.  The speed actually used for a road segment depends on its road category and a speed category defined in the map data and is calculated by linear interpolation between the minimum and maximum speed.
        /// </summary>
        /// <value>The speeds used to calculate the driving times by road category. The first array element represents motorways, the last one pedestrian and cycle paths, see [here](./concepts/road-categories) for more information on road categories.  The speed actually used for a road segment depends on its road category and a speed category defined in the map data and is calculated by linear interpolation between the minimum and maximum speed.</value>
        [DataMember(Name = "speedsByRoadCategory", EmitDefaultValue = false)]
        public List<SpeedByRoadCategory> SpeedsByRoadCategory { get; set; }

        /// <summary>
        /// Specifies the weighting between travel time and travel distance when calculating a route. The value defines the preference for minimizing travel time over minimizing travel distance. - 0: Route is optimized purely for shortest distance. - 100: Route is optimized purely for shortest travel time. - 1-99: A weighted combination of travel time and distance is applied, with higher values     giving more importance to travel time.
        /// </summary>
        /// <value>Specifies the weighting between travel time and travel distance when calculating a route. The value defines the preference for minimizing travel time over minimizing travel distance. - 0: Route is optimized purely for shortest distance. - 100: Route is optimized purely for shortest travel time. - 1-99: A weighted combination of travel time and distance is applied, with higher values     giving more importance to travel time.</value>
        [DataMember(Name = "timePreferenceOverDistance", EmitDefaultValue = true)]
        public int? TimePreferenceOverDistance { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RouteOptions {\n");
            sb.Append("  MaximumSpeed: ").Append(MaximumSpeed).Append("\n");
            sb.Append("  SpeedsByRoadCategory: ").Append(SpeedsByRoadCategory).Append("\n");
            sb.Append("  TimePreferenceOverDistance: ").Append(TimePreferenceOverDistance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // MaximumSpeed (int?) minimum
            if (this.MaximumSpeed < (int?)1)
            {
                yield return new ValidationResult("Invalid value for MaximumSpeed, must be a value greater than or equal to 1.", new [] { "MaximumSpeed" });
            }

            // TimePreferenceOverDistance (int?) maximum
            if (this.TimePreferenceOverDistance > (int?)100)
            {
                yield return new ValidationResult("Invalid value for TimePreferenceOverDistance, must be a value less than or equal to 100.", new [] { "TimePreferenceOverDistance" });
            }

            // TimePreferenceOverDistance (int?) minimum
            if (this.TimePreferenceOverDistance < (int?)0)
            {
                yield return new ValidationResult("Invalid value for TimePreferenceOverDistance, must be a value greater than or equal to 0.", new [] { "TimePreferenceOverDistance" });
            }

            yield break;
        }
    }

}
