/*
 * Data
 *
 * With the Data service you can obtain additional data such as vehicle profiles.
 *
 * The version of the OpenAPI document: 1.9
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.data.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.data.Model
{
    /// <summary>
    /// VehicleModels
    /// </summary>
    [DataContract(Name = "VehicleModels")]
    public partial class VehicleModels : IEquatable<VehicleModels>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VehicleModels" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VehicleModels() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VehicleModels" /> class.
        /// </summary>
        /// <param name="varVehicleModels">A list of model-based vehicles. (required).</param>
        public VehicleModels(List<VehicleModel> varVehicleModels = default(List<VehicleModel>))
        {
            // to ensure "varVehicleModels" is required (not null)
            if (varVehicleModels == null)
            {
                throw new ArgumentNullException("varVehicleModels is a required property for VehicleModels and cannot be null");
            }
            this.VarVehicleModels = varVehicleModels;
        }

        /// <summary>
        /// A list of model-based vehicles.
        /// </summary>
        /// <value>A list of model-based vehicles.</value>
        [DataMember(Name = "vehicleModels", IsRequired = true, EmitDefaultValue = true)]
        public List<VehicleModel> VarVehicleModels { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VehicleModels {\n");
            sb.Append("  VarVehicleModels: ").Append(VarVehicleModels).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VehicleModels);
        }

        /// <summary>
        /// Returns true if VehicleModels instances are equal
        /// </summary>
        /// <param name="input">Instance of VehicleModels to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VehicleModels input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.VarVehicleModels == input.VarVehicleModels ||
                    this.VarVehicleModels != null &&
                    input.VarVehicleModels != null &&
                    this.VarVehicleModels.SequenceEqual(input.VarVehicleModels)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.VarVehicleModels != null)
                {
                    hashCode = (hashCode * 59) + this.VarVehicleModels.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
