/*
 * Data
 * With the Data service you can obtain additional data such as vehicle profiles.
 *
 * The version of the OpenAPI document: 1.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ptvgroup.developer.client.data.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ptvgroup.developer.client.data.model.CombinedTransport;
import com.ptvgroup.developer.client.data.model.Warning;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.ptvgroup.developer.client.data.ApiClient;
/**
 * The combined transports selected by the input parameters.
 */
@JsonPropertyOrder({
  CombinedTransportsResponse.JSON_PROPERTY_COMBINED_TRANSPORTS,
  CombinedTransportsResponse.JSON_PROPERTY_WARNINGS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-12T07:34:48.896153411Z[Etc/UTC]", comments = "Generator version: 7.8.0")
public class CombinedTransportsResponse {
  public static final String JSON_PROPERTY_COMBINED_TRANSPORTS = "combinedTransports";
  private List<CombinedTransport> combinedTransports = new ArrayList<>();

  public static final String JSON_PROPERTY_WARNINGS = "warnings";
  private List<Warning> warnings = new ArrayList<>();

  public CombinedTransportsResponse() { 
  }

  public CombinedTransportsResponse combinedTransports(List<CombinedTransport> combinedTransports) {
    this.combinedTransports = combinedTransports;
    return this;
  }

  public CombinedTransportsResponse addCombinedTransportsItem(CombinedTransport combinedTransportsItem) {
    if (this.combinedTransports == null) {
      this.combinedTransports = new ArrayList<>();
    }
    this.combinedTransports.add(combinedTransportsItem);
    return this;
  }

  /**
   * The list of selected combined transports sorted by ascending distance to the input coordinate.
   * @return combinedTransports
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COMBINED_TRANSPORTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<CombinedTransport> getCombinedTransports() {
    return combinedTransports;
  }


  @JsonProperty(JSON_PROPERTY_COMBINED_TRANSPORTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCombinedTransports(List<CombinedTransport> combinedTransports) {
    this.combinedTransports = combinedTransports;
  }


  public CombinedTransportsResponse warnings(List<Warning> warnings) {
    this.warnings = warnings;
    return this;
  }

  public CombinedTransportsResponse addWarningsItem(Warning warningsItem) {
    if (this.warnings == null) {
      this.warnings = new ArrayList<>();
    }
    this.warnings.add(warningsItem);
    return this;
  }

  /**
   * A list of warnings concerning the validity of the result.
   * @return warnings
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WARNINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<Warning> getWarnings() {
    return warnings;
  }


  @JsonProperty(JSON_PROPERTY_WARNINGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWarnings(List<Warning> warnings) {
    this.warnings = warnings;
  }


  /**
   * Return true if this CombinedTransportsResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CombinedTransportsResponse combinedTransportsResponse = (CombinedTransportsResponse) o;
    return Objects.equals(this.combinedTransports, combinedTransportsResponse.combinedTransports) &&
        Objects.equals(this.warnings, combinedTransportsResponse.warnings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(combinedTransports, warnings);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CombinedTransportsResponse {\n");
    sb.append("    combinedTransports: ").append(toIndentedString(combinedTransports)).append("\n");
    sb.append("    warnings: ").append(toIndentedString(warnings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `combinedTransports` to the URL query string
    if (getCombinedTransports() != null) {
      for (int i = 0; i < getCombinedTransports().size(); i++) {
        if (getCombinedTransports().get(i) != null) {
          joiner.add(getCombinedTransports().get(i).toUrlQueryString(String.format("%scombinedTransports%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `warnings` to the URL query string
    if (getWarnings() != null) {
      for (int i = 0; i < getWarnings().size(); i++) {
        if (getWarnings().get(i) != null) {
          joiner.add(getWarnings().get(i).toUrlQueryString(String.format("%swarnings%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

