/*
 * Data
 * With the Data service you can obtain additional data such as vehicle profiles.
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ptvgroup.developer.client.data.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ptvgroup.developer.client.data.model.CustomRoadAttributeScenario;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * A list of custom road attribute scenarios.
 */
@ApiModel(description = "A list of custom road attribute scenarios.")
@JsonPropertyOrder({
  CustomRoadAttributeScenarioList.JSON_PROPERTY_CUSTOM_ROAD_ATTRIBUTE_SCENARIOS
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-30T06:51:07.244706Z[Etc/UTC]")
public class CustomRoadAttributeScenarioList {
  public static final String JSON_PROPERTY_CUSTOM_ROAD_ATTRIBUTE_SCENARIOS = "customRoadAttributeScenarios";
  private List<CustomRoadAttributeScenario> customRoadAttributeScenarios = null;

  public CustomRoadAttributeScenarioList() { 
  }

  public CustomRoadAttributeScenarioList customRoadAttributeScenarios(List<CustomRoadAttributeScenario> customRoadAttributeScenarios) {
    this.customRoadAttributeScenarios = customRoadAttributeScenarios;
    return this;
  }

  public CustomRoadAttributeScenarioList addCustomRoadAttributeScenariosItem(CustomRoadAttributeScenario customRoadAttributeScenariosItem) {
    if (this.customRoadAttributeScenarios == null) {
      this.customRoadAttributeScenarios = new ArrayList<>();
    }
    this.customRoadAttributeScenarios.add(customRoadAttributeScenariosItem);
    return this;
  }

   /**
   * Get customRoadAttributeScenarios
   * @return customRoadAttributeScenarios
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CUSTOM_ROAD_ATTRIBUTE_SCENARIOS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CustomRoadAttributeScenario> getCustomRoadAttributeScenarios() {
    return customRoadAttributeScenarios;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOM_ROAD_ATTRIBUTE_SCENARIOS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomRoadAttributeScenarios(List<CustomRoadAttributeScenario> customRoadAttributeScenarios) {
    this.customRoadAttributeScenarios = customRoadAttributeScenarios;
  }


  /**
   * Return true if this CustomRoadAttributeScenarioList object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomRoadAttributeScenarioList customRoadAttributeScenarioList = (CustomRoadAttributeScenarioList) o;
    return Objects.equals(this.customRoadAttributeScenarios, customRoadAttributeScenarioList.customRoadAttributeScenarios);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customRoadAttributeScenarios);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomRoadAttributeScenarioList {\n");
    sb.append("    customRoadAttributeScenarios: ").append(toIndentedString(customRoadAttributeScenarios)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

