/*
 * Data
 * With the Data service you can obtain additional data such as vehicle profiles.
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ptvgroup.developer.client.data.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ptvgroup.developer.client.data.model.RoadsToBeAttributed;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * A custom road attribute scenario.
 */
@ApiModel(description = "A custom road attribute scenario.")
@JsonPropertyOrder({
  CustomRoadAttributeScenario.JSON_PROPERTY_ID,
  CustomRoadAttributeScenario.JSON_PROPERTY_NAME,
  CustomRoadAttributeScenario.JSON_PROPERTY_ROADS_TO_BE_ATTRIBUTED,
  CustomRoadAttributeScenario.JSON_PROPERTY_SHARED,
  CustomRoadAttributeScenario.JSON_PROPERTY_ACTIVE,
  CustomRoadAttributeScenario.JSON_PROPERTY_REVISION
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-30T06:51:07.244706Z[Etc/UTC]")
public class CustomRoadAttributeScenario {
  public static final String JSON_PROPERTY_ID = "id";
  private UUID id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_ROADS_TO_BE_ATTRIBUTED = "roadsToBeAttributed";
  private List<RoadsToBeAttributed> roadsToBeAttributed = new ArrayList<>();

  public static final String JSON_PROPERTY_SHARED = "shared";
  private Boolean shared = false;

  public static final String JSON_PROPERTY_ACTIVE = "active";
  private Boolean active = true;

  public static final String JSON_PROPERTY_REVISION = "revision";
  private Integer revision;

  public CustomRoadAttributeScenario() { 
  }

  @JsonCreator
  public CustomRoadAttributeScenario(
    @JsonProperty(JSON_PROPERTY_ID) UUID id
  ) {
  this();
    this.id = id;
  }

   /**
   * The ID of the custom road attribute scenario.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the custom road attribute scenario.")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getId() {
    return id;
  }




  public CustomRoadAttributeScenario name(String name) {
    this.name = name;
    return this;
  }

   /**
   * A user-defined name of the custom road attribute scenario. If specified, it must be unique for the current user. This name can be used in other APIs instead of its ID, then it must not contain a comma.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A user-defined name of the custom road attribute scenario. If specified, it must be unique for the current user. This name can be used in other APIs instead of its ID, then it must not contain a comma.")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public CustomRoadAttributeScenario roadsToBeAttributed(List<RoadsToBeAttributed> roadsToBeAttributed) {
    this.roadsToBeAttributed = roadsToBeAttributed;
    return this;
  }

  public CustomRoadAttributeScenario addRoadsToBeAttributedItem(RoadsToBeAttributed roadsToBeAttributedItem) {
    this.roadsToBeAttributed.add(roadsToBeAttributedItem);
    return this;
  }

   /**
   * A collection of roads to be attributed.
   * @return roadsToBeAttributed
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "A collection of roads to be attributed.")
  @JsonProperty(JSON_PROPERTY_ROADS_TO_BE_ATTRIBUTED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<RoadsToBeAttributed> getRoadsToBeAttributed() {
    return roadsToBeAttributed;
  }


  @JsonProperty(JSON_PROPERTY_ROADS_TO_BE_ATTRIBUTED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRoadsToBeAttributed(List<RoadsToBeAttributed> roadsToBeAttributed) {
    this.roadsToBeAttributed = roadsToBeAttributed;
  }


  public CustomRoadAttributeScenario shared(Boolean shared) {
    this.shared = shared;
    return this;
  }

   /**
   * If true, this custom road attribute scenario can be used by every user by its ID. Other users than the owner cannot modify or delete it nor will it be listed with **getAllCustomRoadAttributeScenarios**.
   * @return shared
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If true, this custom road attribute scenario can be used by every user by its ID. Other users than the owner cannot modify or delete it nor will it be listed with **getAllCustomRoadAttributeScenarios**.")
  @JsonProperty(JSON_PROPERTY_SHARED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getShared() {
    return shared;
  }


  @JsonProperty(JSON_PROPERTY_SHARED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShared(Boolean shared) {
    this.shared = shared;
  }


  public CustomRoadAttributeScenario active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * If false, this custom road attribute scenario will be marked inactive and not used for subsequent route calculations until set active again. This is useful to ignore the scenario without deleting its contents.
   * @return active
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If false, this custom road attribute scenario will be marked inactive and not used for subsequent route calculations until set active again. This is useful to ignore the scenario without deleting its contents.")
  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getActive() {
    return active;
  }


  @JsonProperty(JSON_PROPERTY_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActive(Boolean active) {
    this.active = active;
  }


  public CustomRoadAttributeScenario revision(Integer revision) {
    this.revision = revision;
    return this;
  }

   /**
   * The revision number of the custom road attribute scenario which will automatically be maintained by the server. In responses it will contain the number of updates of this specific scenario. When creating a scenario, it will be ignored. When updating a scenario, pass the number which you got from the server in the corresponding get request to make sure that the scenario has not been changed in the meantime. The server will reject updates for which the revision number does not match the revision stored in the database. When left empty in an update request, any changes will be overwritten.
   * minimum: 0
   * @return revision
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The revision number of the custom road attribute scenario which will automatically be maintained by the server. In responses it will contain the number of updates of this specific scenario. When creating a scenario, it will be ignored. When updating a scenario, pass the number which you got from the server in the corresponding get request to make sure that the scenario has not been changed in the meantime. The server will reject updates for which the revision number does not match the revision stored in the database. When left empty in an update request, any changes will be overwritten.")
  @JsonProperty(JSON_PROPERTY_REVISION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRevision() {
    return revision;
  }


  @JsonProperty(JSON_PROPERTY_REVISION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRevision(Integer revision) {
    this.revision = revision;
  }


  /**
   * Return true if this CustomRoadAttributeScenario object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomRoadAttributeScenario customRoadAttributeScenario = (CustomRoadAttributeScenario) o;
    return Objects.equals(this.id, customRoadAttributeScenario.id) &&
        Objects.equals(this.name, customRoadAttributeScenario.name) &&
        Objects.equals(this.roadsToBeAttributed, customRoadAttributeScenario.roadsToBeAttributed) &&
        Objects.equals(this.shared, customRoadAttributeScenario.shared) &&
        Objects.equals(this.active, customRoadAttributeScenario.active) &&
        Objects.equals(this.revision, customRoadAttributeScenario.revision);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, roadsToBeAttributed, shared, active, revision);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomRoadAttributeScenario {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    roadsToBeAttributed: ").append(toIndentedString(roadsToBeAttributed)).append("\n");
    sb.append("    shared: ").append(toIndentedString(shared)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    revision: ").append(toIndentedString(revision)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

