/*
 * Data
 * With the Data service you can obtain additional data such as vehicle profiles.
 *
 * The version of the OpenAPI document: 1.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ptvgroup.developer.client.data.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ptvgroup.developer.client.data.model.DayOfWeek;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * WeeklyScheduleInterval
 */
@JsonPropertyOrder({
  WeeklyScheduleInterval.JSON_PROPERTY_DAY_OF_WEEK,
  WeeklyScheduleInterval.JSON_PROPERTY_HOUR,
  WeeklyScheduleInterval.JSON_PROPERTY_MINUTE,
  WeeklyScheduleInterval.JSON_PROPERTY_DURATION
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-30T06:51:07.244706Z[Etc/UTC]")
public class WeeklyScheduleInterval {
  public static final String JSON_PROPERTY_DAY_OF_WEEK = "dayOfWeek";
  private DayOfWeek dayOfWeek;

  public static final String JSON_PROPERTY_HOUR = "hour";
  private Integer hour;

  public static final String JSON_PROPERTY_MINUTE = "minute";
  private Integer minute;

  public static final String JSON_PROPERTY_DURATION = "duration";
  private Integer duration;

  public WeeklyScheduleInterval() { 
  }

  public WeeklyScheduleInterval dayOfWeek(DayOfWeek dayOfWeek) {
    this.dayOfWeek = dayOfWeek;
    return this;
  }

   /**
   * Get dayOfWeek
   * @return dayOfWeek
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_DAY_OF_WEEK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public DayOfWeek getDayOfWeek() {
    return dayOfWeek;
  }


  @JsonProperty(JSON_PROPERTY_DAY_OF_WEEK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDayOfWeek(DayOfWeek dayOfWeek) {
    this.dayOfWeek = dayOfWeek;
  }


  public WeeklyScheduleInterval hour(Integer hour) {
    this.hour = hour;
    return this;
  }

   /**
   * The hour the schedule interval starts.
   * minimum: 0
   * maximum: 23
   * @return hour
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "12", required = true, value = "The hour the schedule interval starts.")
  @JsonProperty(JSON_PROPERTY_HOUR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getHour() {
    return hour;
  }


  @JsonProperty(JSON_PROPERTY_HOUR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHour(Integer hour) {
    this.hour = hour;
  }


  public WeeklyScheduleInterval minute(Integer minute) {
    this.minute = minute;
    return this;
  }

   /**
   * The minutes of hours the schedule interval starts.
   * minimum: 0
   * maximum: 59
   * @return minute
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "30", required = true, value = "The minutes of hours the schedule interval starts.")
  @JsonProperty(JSON_PROPERTY_MINUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getMinute() {
    return minute;
  }


  @JsonProperty(JSON_PROPERTY_MINUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMinute(Integer minute) {
    this.minute = minute;
  }


  public WeeklyScheduleInterval duration(Integer duration) {
    this.duration = duration;
    return this;
  }

   /**
   * The duration of the schedule interval in [min].
   * minimum: 1
   * maximum: 10080
   * @return duration
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "360", required = true, value = "The duration of the schedule interval in [min].")
  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getDuration() {
    return duration;
  }


  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDuration(Integer duration) {
    this.duration = duration;
  }


  /**
   * Return true if this WeeklyScheduleInterval object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WeeklyScheduleInterval weeklyScheduleInterval = (WeeklyScheduleInterval) o;
    return Objects.equals(this.dayOfWeek, weeklyScheduleInterval.dayOfWeek) &&
        Objects.equals(this.hour, weeklyScheduleInterval.hour) &&
        Objects.equals(this.minute, weeklyScheduleInterval.minute) &&
        Objects.equals(this.duration, weeklyScheduleInterval.duration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dayOfWeek, hour, minute, duration);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WeeklyScheduleInterval {\n");
    sb.append("    dayOfWeek: ").append(toIndentedString(dayOfWeek)).append("\n");
    sb.append("    hour: ").append(toIndentedString(hour)).append("\n");
    sb.append("    minute: ").append(toIndentedString(minute)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

